DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS upvotes CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  bio VARCHAR(255),
  image VARCHAR(255)
);

CREATE TABLE topics (
  image VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  date_created DATE DEFAULT CURRENT_DATE,
  category VARCHAR(255)
);

CREATE TABLE favourites (
  id SERIAL PIRMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  topic_id INTEGER REFERENCES topics(id) ON DELETE CASCADE
);

CREATE TABLE comments (
  id SERIAL PIRMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  topic_id INTEGER REFERENCES topics(id) ON DELETE CASCADE,
  content VARCHAR(255) NOT NULL
);

CREATE TABLE upvotes (
  id SERIAL PIRMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE
);
